# Makefile - ConnectToVideoServer

.PHONY: all
all: \
 	ConnectToVideoServer


.PHONY: ConnectToVideoServer
ConnectToVideoServer:
	cd ../vcproj/ && $(MAKE) -f ConnectToVideoServer.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f ConnectToVideoServer.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f ConnectToVideoServer.mak depends

