# Makefile - ConnectMoreThan32Channels

.PHONY: all
all: \
 	ConnectMoreThan32Channels


.PHONY: ConnectMoreThan32Channels
ConnectMoreThan32Channels:
	cd ../vcproj/ && $(MAKE) -f ConnectMoreThan32Channels.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f ConnectMoreThan32Channels.mak clean

.PHONY: depends
depends:
	cd  ../vcproj/ && $(MAKE) -f ConnectMoreThan32Channels.mak depends

