# Makefile - GetSetVideoInfo

.PHONY: all
all: \
 	GetSetVideoInfo


.PHONY: GetSetVideoInfo
GetSetVideoInfo:
	cd ../vcproj/ && $(MAKE) -f GetSetVideoInfo.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f GetSetVideoInfo.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f GetSetVideoInfo.mak depends

