# Makefile - SetDO

.PHONY: all
all: \
 	SetDO


.PHONY: SetDO
SetDO:
	cd ../vcproj/ && $(MAKE) -f SetDO.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f SetDO.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f SetDO.mak depends

