# Makefile - GetDI

.PHONY: all
all: \
 	GetDI


.PHONY: GetDI
GetDI:
	cd ../vcproj/ && $(MAKE) -f GetDI.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f GetDI.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f GetDI.mak depends

