# Makefile - SaveToFile

.PHONY: all
all: \
 	SaveToFile


.PHONY: SaveToFile
SaveToFile:
	cd ../vcproj/ && $(MAKE) -f SaveToFile.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f SaveToFile.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f SaveToFile.mak depends

