# Makefile - GetSetNetworkInfo

.PHONY: all
all: \
 	GetSetNetworkInfo


.PHONY: GetSetNetworkInfo
GetSetNetworkInfo:
	cd ../vcproj/ && $(MAKE) -f GetSetNetworkInfo.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f GetSetNetworkInfo.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f GetSetNetworkInfo.mak depends

