# Makefile - NonBlockingSendHTTPCommand

.PHONY: all
all: \
 	NonBlockingSendHTTPCommand


.PHONY: NonBlockingSendHTTPCommand
NonBlockingSendHTTPCommand:
	cd ../vcproj/ && $(MAKE) -f NonBlockingSendHTTPCommand.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f NonBlockingSendHTTPCommand.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f NonBlockingSendHTTPCommand.mak depends

