/********************************************************************************
** Form generated from reading ui file 'cameradialog.ui'
**
** Created: Mon Mar 30 21:53:05 2009
**      by: Qt User Interface Compiler version 4.2.2
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_CAMERADIALOG_H
#define UI_CAMERADIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QDialogButtonBox>
#include <QtGui/QGroupBox>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSlider>
#include <QtGui/QSpinBox>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

class Ui_CameraDialog
{
public:
    QGroupBox *uiGrpSubEncoder;
    QRadioButton *uiRadioSubEncSecondary;
    QRadioButton *uiRadioSubEncPrimary;
    QDialogButtonBox *buttonBox;
    QTabWidget *uiTabSettings;
    QWidget *generalTab;
    QLabel *label_1;
    QLabel *label_23;
    QSpinBox *uiSpinBoxRawVideoFrameRate;
    QGroupBox *osdGroup;
    QLabel *label_14;
    QLabel *uiLableOSDTextNum;
    QLabel *label_16;
    QLineEdit *osdTextEdit;
    QGroupBox *osdDtsGroup;
    QComboBox *osdDtsFormatCombo;
    QLabel *label_15;
    QLineEdit *uiLEditTLy;
    QSpinBox *uiSpinBoxOSDNum;
    QComboBox *osdLocationCombo;
    QCheckBox *uiChkBoxOSDShow;
    QLabel *uiLableTLy;
    QLineEdit *uiLEditTLx;
    QLabel *uiLableTLx;
    QLabel *uiLabelTranslucent;
    QLabel *uiLabelTranslucentValue;
    QSlider *uiHSliderTranslucent;
    QLineEdit *cameraNameEdit;
    QWidget *encodingTab;
    QGroupBox *JPEGGroup;
    QLabel *label_8;
    QLineEdit *jpegQualityEdit;
    QGroupBox *uiGrpEncMPEG4;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_24;
    QLineEdit *uiLEditEncGOPMPEG4;
    QComboBox *uiComboBitRateControlMPEG4;
    QLineEdit *uiLEditAvgBitRateMPEG4;
    QLineEdit *uiLEditMaxBitRateMPEG4;
    QLineEdit *uiLEditQualityMPEG4;
    QLabel *uiLabelQualityMPEG4;
    QLabel *label_2;
    QLabel *label_3;
    QComboBox *decimationCombo;
    QLineEdit *frameRateEdit;
    QGroupBox *H264Group;
    QLabel *label_6;
    QLabel *label_17;
    QLabel *label_7;
    QLabel *label_5;
    QLabel *label_4;
    QLineEdit *h264QualityEdit;
    QComboBox *bitRateControlCombo;
    QLineEdit *GOPSizeEdit;
    QLineEdit *maxBitRateEdit;
    QLineEdit *avgBitRateEdit;
    QWidget *alarmsTab;
    QGroupBox *blindDetectionGroup;
    QLabel *label_10;
    QLineEdit *blindThresholdEdit;
    QPushButton *uiBtnBlindRegions;
    QGroupBox *nightDetectionGroup;
    QLabel *label_9;
    QLineEdit *nightThresholdEdit;
    QGroupBox *motionDetectionGroup;
    QPushButton *uiBtnMotionRegions;
    QLineEdit *motionThresholdEdit;
    QComboBox *uiComboMDThresholds;
    QGroupBox *privacyProtectionGroup;
    QPushButton *uiBtnPrivacyRegions;
    QLabel *uiLabelMotionValueFreq;
    QLineEdit *uiLEditMotionValueFreq;
    QWidget *uiTabEncOnAlarm;
    QGroupBox *uiGrpEncOnAlarmMPEG4;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_37;
    QLineEdit *uiLEditEncOnAlarmMaxBitRateMPEG4;
    QLineEdit *uiLEditEncOnAlarmAvgBitRateMPEG4;
    QComboBox *uiComboEncOnAlarmBitRateControlMPEG4;
    QLineEdit *uiLEditEncOnAlarmGOPMPEG4;
    QLineEdit *uiLEditEncOnAlarmQualityMPEG4;
    QLabel *uiLabelEncOnAlarmQualityMPEG4;
    QGroupBox *uiGrpEncOnAlarmMjpeg;
    QLabel *uiLabelEncOnAlarmMjpegQuality;
    QLineEdit *uiLEditEncOnAlarmMjpegQuality;
    QLabel *label_20;
    QLabel *label;
    QLabel *label_21;
    QGroupBox *uiGrpEncOnAlarmH264;
    QLabel *label_18;
    QLabel *label_13;
    QLabel *label_12;
    QLabel *label_22;
    QLabel *label_19;
    QLineEdit *onAlarmGOPSizeEdit;
    QComboBox *onAlarmBitRateControlCombo;
    QLineEdit *onAlarmAvgBitRateEdit;
    QLineEdit *onAlarmMaxBitRateEdit;
    QLineEdit *onAlarmH264QualityEdit;
    QCheckBox *onAlarmEncodingCheck;
    QLineEdit *onAlarmMinOffEdit;
    QLineEdit *onAlarmMinOnEdit;
    QLineEdit *onAlarmFrameRateEdit;
    QWidget *uiTabVideoIn;
    QLabel *uiLabelBrightness;
    QLabel *uiLabelContrast;
    QLabel *uiLabelHue;
    QSlider *uiHSliderBrightness;
    QSlider *uiHSliderContrast;
    QLabel *uiLabelHueValue;
    QLabel *uiLabelBrightnessValue;
    QLabel *uiLabelContrastValue;
    QLabel *uiLabelSaturation;
    QLabel *uiLabelSaturationValue;
    QLabel *uiLabelSharpness;
    QSlider *uiHSliderHue;
    QCheckBox *uiChkBoxLiveUpdate;
    QPushButton *uiBtnResetAll;
    QLabel *uiLabelSharpnessValue;
    QSlider *uiHSliderSaturation;
    QCheckBox *uiChkBoxDeinterlacing;
    QLabel *uiLabelGainMode;
    QSlider *uiHSliderSharpness;
    QLabel *uiLabelGainModeValue;
    QCheckBox *uiChkBoxNoiseReduction;
    QLabel *uiLabelCamTermination;
    QSlider *uiHSliderGainMode;
    QComboBox *uiComboBoxCamTermination;
    QWidget *uiTabAudioEncoder;
    QLabel *uiLabelAudioEncoder;
    QLabel *uiLabelAudioEncoderValue;
    QRadioButton *uiRadioAlaw;
    QRadioButton *uiRadioUlaw;

    void setupUi(QDialog *CameraDialog)
    {
    CameraDialog->setObjectName(QString::fromUtf8("CameraDialog"));
    QSizePolicy sizePolicy(static_cast<QSizePolicy::Policy>(0), static_cast<QSizePolicy::Policy>(0));
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(CameraDialog->sizePolicy().hasHeightForWidth());
    CameraDialog->setSizePolicy(sizePolicy);
    CameraDialog->setMinimumSize(QSize(492, 390));
    CameraDialog->setMaximumSize(QSize(492, 392));
    uiGrpSubEncoder = new QGroupBox(CameraDialog);
    uiGrpSubEncoder->setObjectName(QString::fromUtf8("uiGrpSubEncoder"));
    uiGrpSubEncoder->setGeometry(QRect(10, 330, 241, 51));
    uiRadioSubEncSecondary = new QRadioButton(uiGrpSubEncoder);
    uiRadioSubEncSecondary->setObjectName(QString::fromUtf8("uiRadioSubEncSecondary"));
    uiRadioSubEncSecondary->setGeometry(QRect(120, 20, 95, 21));
    uiRadioSubEncPrimary = new QRadioButton(uiGrpSubEncoder);
    uiRadioSubEncPrimary->setObjectName(QString::fromUtf8("uiRadioSubEncPrimary"));
    uiRadioSubEncPrimary->setGeometry(QRect(20, 20, 81, 21));
    uiRadioSubEncPrimary->setChecked(true);
    buttonBox = new QDialogButtonBox(CameraDialog);
    buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
    buttonBox->setGeometry(QRect(305, 340, 180, 40));
    buttonBox->setOrientation(Qt::Horizontal);
    buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::NoButton|QDialogButtonBox::Ok);
    buttonBox->setCenterButtons(true);
    uiTabSettings = new QTabWidget(CameraDialog);
    uiTabSettings->setObjectName(QString::fromUtf8("uiTabSettings"));
    uiTabSettings->setGeometry(QRect(10, 10, 471, 321));
    generalTab = new QWidget();
    generalTab->setObjectName(QString::fromUtf8("generalTab"));
    label_1 = new QLabel(generalTab);
    label_1->setObjectName(QString::fromUtf8("label_1"));
    label_1->setGeometry(QRect(10, 10, 94, 21));
    label_1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_23 = new QLabel(generalTab);
    label_23->setObjectName(QString::fromUtf8("label_23"));
    label_23->setGeometry(QRect(20, 260, 151, 17));
    uiSpinBoxRawVideoFrameRate = new QSpinBox(generalTab);
    uiSpinBoxRawVideoFrameRate->setObjectName(QString::fromUtf8("uiSpinBoxRawVideoFrameRate"));
    uiSpinBoxRawVideoFrameRate->setGeometry(QRect(168, 258, 48, 23));
    osdGroup = new QGroupBox(generalTab);
    osdGroup->setObjectName(QString::fromUtf8("osdGroup"));
    osdGroup->setGeometry(QRect(20, 40, 431, 211));
    osdGroup->setCheckable(true);
    label_14 = new QLabel(osdGroup);
    label_14->setObjectName(QString::fromUtf8("label_14"));
    label_14->setGeometry(QRect(6, 46, 60, 21));
    label_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLableOSDTextNum = new QLabel(osdGroup);
    uiLableOSDTextNum->setObjectName(QString::fromUtf8("uiLableOSDTextNum"));
    uiLableOSDTextNum->setGeometry(QRect(6, 20, 60, 21));
    uiLableOSDTextNum->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_16 = new QLabel(osdGroup);
    label_16->setObjectName(QString::fromUtf8("label_16"));
    label_16->setGeometry(QRect(6, 76, 60, 21));
    label_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    osdTextEdit = new QLineEdit(osdGroup);
    osdTextEdit->setObjectName(QString::fromUtf8("osdTextEdit"));
    osdTextEdit->setGeometry(QRect(76, 46, 345, 23));
    osdDtsGroup = new QGroupBox(osdGroup);
    osdDtsGroup->setObjectName(QString::fromUtf8("osdDtsGroup"));
    osdDtsGroup->setGeometry(QRect(9, 150, 211, 51));
    osdDtsGroup->setCheckable(true);
    osdDtsFormatCombo = new QComboBox(osdDtsGroup);
    osdDtsFormatCombo->setObjectName(QString::fromUtf8("osdDtsFormatCombo"));
    osdDtsFormatCombo->setGeometry(QRect(84, 24, 121, 22));
    label_15 = new QLabel(osdDtsGroup);
    label_15->setObjectName(QString::fromUtf8("label_15"));
    label_15->setGeometry(QRect(23, 24, 51, 20));
    label_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLEditTLy = new QLineEdit(osdGroup);
    uiLEditTLy->setObjectName(QString::fromUtf8("uiLEditTLy"));
    uiLEditTLy->setEnabled(false);
    uiLEditTLy->setGeometry(QRect(386, 78, 36, 23));
    uiLEditTLy->setMaxLength(4);
    uiSpinBoxOSDNum = new QSpinBox(osdGroup);
    uiSpinBoxOSDNum->setObjectName(QString::fromUtf8("uiSpinBoxOSDNum"));
    uiSpinBoxOSDNum->setGeometry(QRect(77, 17, 48, 23));
    uiSpinBoxOSDNum->setMaximum(1);
    uiSpinBoxOSDNum->setMinimum(1);
    uiSpinBoxOSDNum->setValue(1);
    osdLocationCombo = new QComboBox(osdGroup);
    osdLocationCombo->setObjectName(QString::fromUtf8("osdLocationCombo"));
    osdLocationCombo->setGeometry(QRect(76, 76, 121, 22));
    uiChkBoxOSDShow = new QCheckBox(osdGroup);
    uiChkBoxOSDShow->setObjectName(QString::fromUtf8("uiChkBoxOSDShow"));
    uiChkBoxOSDShow->setGeometry(QRect(331, 180, 81, 21));
    uiLableTLy = new QLabel(osdGroup);
    uiLableTLy->setObjectName(QString::fromUtf8("uiLableTLy"));
    uiLableTLy->setEnabled(false);
    uiLableTLy->setGeometry(QRect(316, 80, 61, 20));
    uiLableTLy->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLEditTLx = new QLineEdit(osdGroup);
    uiLEditTLx->setObjectName(QString::fromUtf8("uiLEditTLx"));
    uiLEditTLx->setEnabled(false);
    uiLEditTLx->setGeometry(QRect(272, 78, 36, 23));
    uiLEditTLx->setMaxLength(4);
    uiLableTLx = new QLabel(osdGroup);
    uiLableTLx->setObjectName(QString::fromUtf8("uiLableTLx"));
    uiLableTLx->setEnabled(false);
    uiLableTLx->setGeometry(QRect(210, 80, 60, 17));
    uiLableTLx->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLabelTranslucent = new QLabel(osdGroup);
    uiLabelTranslucent->setObjectName(QString::fromUtf8("uiLabelTranslucent"));
    uiLabelTranslucent->setEnabled(false);
    uiLabelTranslucent->setGeometry(QRect(10, 117, 101, 17));
    uiLabelTranslucent->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLabelTranslucentValue = new QLabel(osdGroup);
    uiLabelTranslucentValue->setObjectName(QString::fromUtf8("uiLabelTranslucentValue"));
    uiLabelTranslucentValue->setEnabled(false);
    uiLabelTranslucentValue->setGeometry(QRect(120, 117, 31, 17));
    uiLabelTranslucentValue->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiHSliderTranslucent = new QSlider(osdGroup);
    uiHSliderTranslucent->setObjectName(QString::fromUtf8("uiHSliderTranslucent"));
    uiHSliderTranslucent->setEnabled(false);
    uiHSliderTranslucent->setGeometry(QRect(160, 117, 251, 21));
    uiHSliderTranslucent->setMaximum(255);
    uiHSliderTranslucent->setOrientation(Qt::Horizontal);
    cameraNameEdit = new QLineEdit(generalTab);
    cameraNameEdit->setObjectName(QString::fromUtf8("cameraNameEdit"));
    cameraNameEdit->setGeometry(QRect(113, 10, 121, 20));
    uiTabSettings->addTab(generalTab, QApplication::translate("CameraDialog", "General", 0, QApplication::UnicodeUTF8));
    encodingTab = new QWidget();
    encodingTab->setObjectName(QString::fromUtf8("encodingTab"));
    JPEGGroup = new QGroupBox(encodingTab);
    JPEGGroup->setObjectName(QString::fromUtf8("JPEGGroup"));
    JPEGGroup->setGeometry(QRect(220, 30, 221, 111));
    JPEGGroup->setCheckable(false);
    JPEGGroup->setChecked(false);
    label_8 = new QLabel(JPEGGroup);
    label_8->setObjectName(QString::fromUtf8("label_8"));
    label_8->setGeometry(QRect(40, 30, 51, 21));
    label_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    jpegQualityEdit = new QLineEdit(JPEGGroup);
    jpegQualityEdit->setObjectName(QString::fromUtf8("jpegQualityEdit"));
    jpegQualityEdit->setGeometry(QRect(100, 30, 71, 20));
    uiGrpEncMPEG4 = new QGroupBox(encodingTab);
    uiGrpEncMPEG4->setObjectName(QString::fromUtf8("uiGrpEncMPEG4"));
    uiGrpEncMPEG4->setGeometry(QRect(220, 30, 221, 231));
    uiGrpEncMPEG4->setAlignment(Qt::AlignLeading);
    uiGrpEncMPEG4->setCheckable(false);
    uiGrpEncMPEG4->setChecked(false);
    label_25 = new QLabel(uiGrpEncMPEG4);
    label_25->setObjectName(QString::fromUtf8("label_25"));
    label_25->setGeometry(QRect(10, 70, 108, 21));
    label_25->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_26 = new QLabel(uiGrpEncMPEG4);
    label_26->setObjectName(QString::fromUtf8("label_26"));
    label_26->setGeometry(QRect(10, 110, 108, 21));
    label_26->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_27 = new QLabel(uiGrpEncMPEG4);
    label_27->setObjectName(QString::fromUtf8("label_27"));
    label_27->setGeometry(QRect(10, 150, 108, 20));
    label_27->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_24 = new QLabel(uiGrpEncMPEG4);
    label_24->setObjectName(QString::fromUtf8("label_24"));
    label_24->setGeometry(QRect(10, 30, 108, 21));
    label_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLEditEncGOPMPEG4 = new QLineEdit(uiGrpEncMPEG4);
    uiLEditEncGOPMPEG4->setObjectName(QString::fromUtf8("uiLEditEncGOPMPEG4"));
    uiLEditEncGOPMPEG4->setGeometry(QRect(122, 30, 71, 20));
    uiComboBitRateControlMPEG4 = new QComboBox(uiGrpEncMPEG4);
    uiComboBitRateControlMPEG4->setObjectName(QString::fromUtf8("uiComboBitRateControlMPEG4"));
    uiComboBitRateControlMPEG4->setGeometry(QRect(122, 70, 71, 22));
    uiLEditAvgBitRateMPEG4 = new QLineEdit(uiGrpEncMPEG4);
    uiLEditAvgBitRateMPEG4->setObjectName(QString::fromUtf8("uiLEditAvgBitRateMPEG4"));
    uiLEditAvgBitRateMPEG4->setGeometry(QRect(122, 110, 71, 20));
    uiLEditMaxBitRateMPEG4 = new QLineEdit(uiGrpEncMPEG4);
    uiLEditMaxBitRateMPEG4->setObjectName(QString::fromUtf8("uiLEditMaxBitRateMPEG4"));
    uiLEditMaxBitRateMPEG4->setGeometry(QRect(122, 150, 71, 20));
    uiLEditQualityMPEG4 = new QLineEdit(uiGrpEncMPEG4);
    uiLEditQualityMPEG4->setObjectName(QString::fromUtf8("uiLEditQualityMPEG4"));
    uiLEditQualityMPEG4->setGeometry(QRect(122, 190, 71, 20));
    uiLabelQualityMPEG4 = new QLabel(uiGrpEncMPEG4);
    uiLabelQualityMPEG4->setObjectName(QString::fromUtf8("uiLabelQualityMPEG4"));
    uiLabelQualityMPEG4->setGeometry(QRect(10, 190, 108, 21));
    uiLabelQualityMPEG4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_2 = new QLabel(encodingTab);
    label_2->setObjectName(QString::fromUtf8("label_2"));
    label_2->setGeometry(QRect(10, 40, 91, 21));
    label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_3 = new QLabel(encodingTab);
    label_3->setObjectName(QString::fromUtf8("label_3"));
    label_3->setGeometry(QRect(20, 80, 81, 21));
    label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    decimationCombo = new QComboBox(encodingTab);
    decimationCombo->setObjectName(QString::fromUtf8("decimationCombo"));
    decimationCombo->setGeometry(QRect(110, 40, 67, 22));
    frameRateEdit = new QLineEdit(encodingTab);
    frameRateEdit->setObjectName(QString::fromUtf8("frameRateEdit"));
    frameRateEdit->setGeometry(QRect(110, 80, 67, 20));
    H264Group = new QGroupBox(encodingTab);
    H264Group->setObjectName(QString::fromUtf8("H264Group"));
    H264Group->setGeometry(QRect(220, 30, 221, 231));
    H264Group->setAlignment(Qt::AlignLeading);
    H264Group->setCheckable(false);
    H264Group->setChecked(false);
    label_6 = new QLabel(H264Group);
    label_6->setObjectName(QString::fromUtf8("label_6"));
    label_6->setGeometry(QRect(10, 110, 108, 21));
    label_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_17 = new QLabel(H264Group);
    label_17->setObjectName(QString::fromUtf8("label_17"));
    label_17->setGeometry(QRect(10, 150, 108, 20));
    label_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_7 = new QLabel(H264Group);
    label_7->setObjectName(QString::fromUtf8("label_7"));
    label_7->setGeometry(QRect(10, 190, 108, 21));
    label_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_5 = new QLabel(H264Group);
    label_5->setObjectName(QString::fromUtf8("label_5"));
    label_5->setGeometry(QRect(10, 70, 108, 21));
    label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_4 = new QLabel(H264Group);
    label_4->setObjectName(QString::fromUtf8("label_4"));
    label_4->setGeometry(QRect(10, 30, 108, 21));
    label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    h264QualityEdit = new QLineEdit(H264Group);
    h264QualityEdit->setObjectName(QString::fromUtf8("h264QualityEdit"));
    h264QualityEdit->setGeometry(QRect(122, 190, 71, 20));
    bitRateControlCombo = new QComboBox(H264Group);
    bitRateControlCombo->setObjectName(QString::fromUtf8("bitRateControlCombo"));
    bitRateControlCombo->setGeometry(QRect(122, 70, 71, 22));
    GOPSizeEdit = new QLineEdit(H264Group);
    GOPSizeEdit->setObjectName(QString::fromUtf8("GOPSizeEdit"));
    GOPSizeEdit->setGeometry(QRect(122, 30, 71, 20));
    maxBitRateEdit = new QLineEdit(H264Group);
    maxBitRateEdit->setObjectName(QString::fromUtf8("maxBitRateEdit"));
    maxBitRateEdit->setGeometry(QRect(122, 150, 71, 20));
    avgBitRateEdit = new QLineEdit(H264Group);
    avgBitRateEdit->setObjectName(QString::fromUtf8("avgBitRateEdit"));
    avgBitRateEdit->setGeometry(QRect(122, 110, 71, 20));
    uiTabSettings->addTab(encodingTab, QApplication::translate("CameraDialog", "Video Encoder", 0, QApplication::UnicodeUTF8));
    alarmsTab = new QWidget();
    alarmsTab->setObjectName(QString::fromUtf8("alarmsTab"));
    blindDetectionGroup = new QGroupBox(alarmsTab);
    blindDetectionGroup->setObjectName(QString::fromUtf8("blindDetectionGroup"));
    blindDetectionGroup->setGeometry(QRect(240, 30, 201, 101));
    blindDetectionGroup->setCheckable(true);
    blindDetectionGroup->setChecked(false);
    label_10 = new QLabel(blindDetectionGroup);
    label_10->setObjectName(QString::fromUtf8("label_10"));
    label_10->setGeometry(QRect(10, 30, 71, 21));
    label_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    blindThresholdEdit = new QLineEdit(blindDetectionGroup);
    blindThresholdEdit->setObjectName(QString::fromUtf8("blindThresholdEdit"));
    blindThresholdEdit->setGeometry(QRect(90, 30, 71, 20));
    uiBtnBlindRegions = new QPushButton(blindDetectionGroup);
    uiBtnBlindRegions->setObjectName(QString::fromUtf8("uiBtnBlindRegions"));
    uiBtnBlindRegions->setGeometry(QRect(90, 60, 75, 25));
    nightDetectionGroup = new QGroupBox(alarmsTab);
    nightDetectionGroup->setObjectName(QString::fromUtf8("nightDetectionGroup"));
    nightDetectionGroup->setGeometry(QRect(20, 150, 201, 71));
    nightDetectionGroup->setCheckable(true);
    nightDetectionGroup->setChecked(false);
    label_9 = new QLabel(nightDetectionGroup);
    label_9->setObjectName(QString::fromUtf8("label_9"));
    label_9->setGeometry(QRect(10, 30, 71, 21));
    label_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    nightThresholdEdit = new QLineEdit(nightDetectionGroup);
    nightThresholdEdit->setObjectName(QString::fromUtf8("nightThresholdEdit"));
    nightThresholdEdit->setGeometry(QRect(90, 30, 71, 20));
    motionDetectionGroup = new QGroupBox(alarmsTab);
    motionDetectionGroup->setObjectName(QString::fromUtf8("motionDetectionGroup"));
    motionDetectionGroup->setGeometry(QRect(20, 30, 201, 101));
    motionDetectionGroup->setCheckable(true);
    motionDetectionGroup->setChecked(false);
    uiBtnMotionRegions = new QPushButton(motionDetectionGroup);
    uiBtnMotionRegions->setObjectName(QString::fromUtf8("uiBtnMotionRegions"));
    uiBtnMotionRegions->setGeometry(QRect(90, 60, 75, 25));
    motionThresholdEdit = new QLineEdit(motionDetectionGroup);
    motionThresholdEdit->setObjectName(QString::fromUtf8("motionThresholdEdit"));
    motionThresholdEdit->setGeometry(QRect(158, 30, 31, 23));
    uiComboMDThresholds = new QComboBox(motionDetectionGroup);
    uiComboMDThresholds->setObjectName(QString::fromUtf8("uiComboMDThresholds"));
    uiComboMDThresholds->setGeometry(QRect(10, 31, 141, 22));
    privacyProtectionGroup = new QGroupBox(alarmsTab);
    privacyProtectionGroup->setObjectName(QString::fromUtf8("privacyProtectionGroup"));
    privacyProtectionGroup->setEnabled(true);
    privacyProtectionGroup->setGeometry(QRect(240, 150, 201, 71));
    privacyProtectionGroup->setCheckable(true);
    privacyProtectionGroup->setChecked(false);
    uiBtnPrivacyRegions = new QPushButton(privacyProtectionGroup);
    uiBtnPrivacyRegions->setObjectName(QString::fromUtf8("uiBtnPrivacyRegions"));
    uiBtnPrivacyRegions->setGeometry(QRect(90, 30, 75, 25));
    uiLabelMotionValueFreq = new QLabel(alarmsTab);
    uiLabelMotionValueFreq->setObjectName(QString::fromUtf8("uiLabelMotionValueFreq"));
    uiLabelMotionValueFreq->setGeometry(QRect(21, 250, 191, 20));
    uiLabelMotionValueFreq->setLayoutDirection(Qt::LeftToRight);
    uiLabelMotionValueFreq->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
    uiLEditMotionValueFreq = new QLineEdit(alarmsTab);
    uiLEditMotionValueFreq->setObjectName(QString::fromUtf8("uiLEditMotionValueFreq"));
    uiLEditMotionValueFreq->setGeometry(QRect(221, 250, 49, 21));
    uiLEditMotionValueFreq->setMaxLength(3);
    uiTabSettings->addTab(alarmsTab, QApplication::translate("CameraDialog", "Alarms", 0, QApplication::UnicodeUTF8));
    uiTabEncOnAlarm = new QWidget();
    uiTabEncOnAlarm->setObjectName(QString::fromUtf8("uiTabEncOnAlarm"));
    uiGrpEncOnAlarmMPEG4 = new QGroupBox(uiTabEncOnAlarm);
    uiGrpEncOnAlarmMPEG4->setObjectName(QString::fromUtf8("uiGrpEncOnAlarmMPEG4"));
    uiGrpEncOnAlarmMPEG4->setGeometry(QRect(220, 30, 231, 231));
    uiGrpEncOnAlarmMPEG4->setAlignment(Qt::AlignLeading);
    uiGrpEncOnAlarmMPEG4->setCheckable(false);
    uiGrpEncOnAlarmMPEG4->setChecked(false);
    label_33 = new QLabel(uiGrpEncOnAlarmMPEG4);
    label_33->setObjectName(QString::fromUtf8("label_33"));
    label_33->setGeometry(QRect(10, 150, 108, 20));
    label_33->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_34 = new QLabel(uiGrpEncOnAlarmMPEG4);
    label_34->setObjectName(QString::fromUtf8("label_34"));
    label_34->setGeometry(QRect(10, 70, 108, 21));
    label_34->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_35 = new QLabel(uiGrpEncOnAlarmMPEG4);
    label_35->setObjectName(QString::fromUtf8("label_35"));
    label_35->setGeometry(QRect(10, 110, 108, 21));
    label_35->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_37 = new QLabel(uiGrpEncOnAlarmMPEG4);
    label_37->setObjectName(QString::fromUtf8("label_37"));
    label_37->setGeometry(QRect(10, 30, 108, 21));
    label_37->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLEditEncOnAlarmMaxBitRateMPEG4 = new QLineEdit(uiGrpEncOnAlarmMPEG4);
    uiLEditEncOnAlarmMaxBitRateMPEG4->setObjectName(QString::fromUtf8("uiLEditEncOnAlarmMaxBitRateMPEG4"));
    uiLEditEncOnAlarmMaxBitRateMPEG4->setGeometry(QRect(122, 150, 71, 20));
    uiLEditEncOnAlarmAvgBitRateMPEG4 = new QLineEdit(uiGrpEncOnAlarmMPEG4);
    uiLEditEncOnAlarmAvgBitRateMPEG4->setObjectName(QString::fromUtf8("uiLEditEncOnAlarmAvgBitRateMPEG4"));
    uiLEditEncOnAlarmAvgBitRateMPEG4->setGeometry(QRect(122, 110, 71, 20));
    uiComboEncOnAlarmBitRateControlMPEG4 = new QComboBox(uiGrpEncOnAlarmMPEG4);
    uiComboEncOnAlarmBitRateControlMPEG4->setObjectName(QString::fromUtf8("uiComboEncOnAlarmBitRateControlMPEG4"));
    uiComboEncOnAlarmBitRateControlMPEG4->setGeometry(QRect(122, 70, 71, 22));
    uiLEditEncOnAlarmGOPMPEG4 = new QLineEdit(uiGrpEncOnAlarmMPEG4);
    uiLEditEncOnAlarmGOPMPEG4->setObjectName(QString::fromUtf8("uiLEditEncOnAlarmGOPMPEG4"));
    uiLEditEncOnAlarmGOPMPEG4->setGeometry(QRect(122, 30, 71, 20));
    uiLEditEncOnAlarmQualityMPEG4 = new QLineEdit(uiGrpEncOnAlarmMPEG4);
    uiLEditEncOnAlarmQualityMPEG4->setObjectName(QString::fromUtf8("uiLEditEncOnAlarmQualityMPEG4"));
    uiLEditEncOnAlarmQualityMPEG4->setGeometry(QRect(122, 190, 71, 20));
    uiLabelEncOnAlarmQualityMPEG4 = new QLabel(uiGrpEncOnAlarmMPEG4);
    uiLabelEncOnAlarmQualityMPEG4->setObjectName(QString::fromUtf8("uiLabelEncOnAlarmQualityMPEG4"));
    uiLabelEncOnAlarmQualityMPEG4->setGeometry(QRect(10, 190, 108, 21));
    uiLabelEncOnAlarmQualityMPEG4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiGrpEncOnAlarmMjpeg = new QGroupBox(uiTabEncOnAlarm);
    uiGrpEncOnAlarmMjpeg->setObjectName(QString::fromUtf8("uiGrpEncOnAlarmMjpeg"));
    uiGrpEncOnAlarmMjpeg->setGeometry(QRect(220, 30, 231, 231));
    uiLabelEncOnAlarmMjpegQuality = new QLabel(uiGrpEncOnAlarmMjpeg);
    uiLabelEncOnAlarmMjpegQuality->setObjectName(QString::fromUtf8("uiLabelEncOnAlarmMjpegQuality"));
    uiLabelEncOnAlarmMjpegQuality->setGeometry(QRect(10, 30, 108, 21));
    uiLabelEncOnAlarmMjpegQuality->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLEditEncOnAlarmMjpegQuality = new QLineEdit(uiGrpEncOnAlarmMjpeg);
    uiLEditEncOnAlarmMjpegQuality->setObjectName(QString::fromUtf8("uiLEditEncOnAlarmMjpegQuality"));
    uiLEditEncOnAlarmMjpegQuality->setGeometry(QRect(122, 30, 71, 20));
    label_20 = new QLabel(uiTabEncOnAlarm);
    label_20->setObjectName(QString::fromUtf8("label_20"));
    label_20->setGeometry(QRect(12, 160, 121, 21));
    label_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label = new QLabel(uiTabEncOnAlarm);
    label->setObjectName(QString::fromUtf8("label"));
    label->setGeometry(QRect(12, 120, 121, 21));
    label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_21 = new QLabel(uiTabEncOnAlarm);
    label_21->setObjectName(QString::fromUtf8("label_21"));
    label_21->setGeometry(QRect(12, 80, 121, 21));
    label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiGrpEncOnAlarmH264 = new QGroupBox(uiTabEncOnAlarm);
    uiGrpEncOnAlarmH264->setObjectName(QString::fromUtf8("uiGrpEncOnAlarmH264"));
    uiGrpEncOnAlarmH264->setGeometry(QRect(220, 30, 231, 231));
    uiGrpEncOnAlarmH264->setAlignment(Qt::AlignLeading);
    uiGrpEncOnAlarmH264->setCheckable(false);
    uiGrpEncOnAlarmH264->setChecked(false);
    label_18 = new QLabel(uiGrpEncOnAlarmH264);
    label_18->setObjectName(QString::fromUtf8("label_18"));
    label_18->setGeometry(QRect(10, 150, 108, 20));
    label_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_13 = new QLabel(uiGrpEncOnAlarmH264);
    label_13->setObjectName(QString::fromUtf8("label_13"));
    label_13->setGeometry(QRect(10, 70, 108, 21));
    label_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_12 = new QLabel(uiGrpEncOnAlarmH264);
    label_12->setObjectName(QString::fromUtf8("label_12"));
    label_12->setGeometry(QRect(10, 110, 108, 21));
    label_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_22 = new QLabel(uiGrpEncOnAlarmH264);
    label_22->setObjectName(QString::fromUtf8("label_22"));
    label_22->setGeometry(QRect(10, 190, 108, 21));
    label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    label_19 = new QLabel(uiGrpEncOnAlarmH264);
    label_19->setObjectName(QString::fromUtf8("label_19"));
    label_19->setGeometry(QRect(10, 30, 108, 21));
    label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    onAlarmGOPSizeEdit = new QLineEdit(uiGrpEncOnAlarmH264);
    onAlarmGOPSizeEdit->setObjectName(QString::fromUtf8("onAlarmGOPSizeEdit"));
    onAlarmGOPSizeEdit->setGeometry(QRect(122, 30, 71, 20));
    onAlarmBitRateControlCombo = new QComboBox(uiGrpEncOnAlarmH264);
    onAlarmBitRateControlCombo->setObjectName(QString::fromUtf8("onAlarmBitRateControlCombo"));
    onAlarmBitRateControlCombo->setGeometry(QRect(122, 70, 71, 22));
    onAlarmAvgBitRateEdit = new QLineEdit(uiGrpEncOnAlarmH264);
    onAlarmAvgBitRateEdit->setObjectName(QString::fromUtf8("onAlarmAvgBitRateEdit"));
    onAlarmAvgBitRateEdit->setGeometry(QRect(122, 110, 71, 20));
    onAlarmMaxBitRateEdit = new QLineEdit(uiGrpEncOnAlarmH264);
    onAlarmMaxBitRateEdit->setObjectName(QString::fromUtf8("onAlarmMaxBitRateEdit"));
    onAlarmMaxBitRateEdit->setGeometry(QRect(122, 150, 71, 20));
    onAlarmH264QualityEdit = new QLineEdit(uiGrpEncOnAlarmH264);
    onAlarmH264QualityEdit->setObjectName(QString::fromUtf8("onAlarmH264QualityEdit"));
    onAlarmH264QualityEdit->setGeometry(QRect(122, 190, 71, 20));
    onAlarmEncodingCheck = new QCheckBox(uiTabEncOnAlarm);
    onAlarmEncodingCheck->setObjectName(QString::fromUtf8("onAlarmEncodingCheck"));
    onAlarmEncodingCheck->setGeometry(QRect(10, 30, 181, 20));
    onAlarmMinOffEdit = new QLineEdit(uiTabEncOnAlarm);
    onAlarmMinOffEdit->setObjectName(QString::fromUtf8("onAlarmMinOffEdit"));
    onAlarmMinOffEdit->setGeometry(QRect(140, 160, 71, 23));
    onAlarmMinOnEdit = new QLineEdit(uiTabEncOnAlarm);
    onAlarmMinOnEdit->setObjectName(QString::fromUtf8("onAlarmMinOnEdit"));
    onAlarmMinOnEdit->setGeometry(QRect(140, 120, 71, 23));
    onAlarmFrameRateEdit = new QLineEdit(uiTabEncOnAlarm);
    onAlarmFrameRateEdit->setObjectName(QString::fromUtf8("onAlarmFrameRateEdit"));
    onAlarmFrameRateEdit->setGeometry(QRect(140, 80, 71, 20));
    uiTabSettings->addTab(uiTabEncOnAlarm, QApplication::translate("CameraDialog", "Video Encoder on Alarm", 0, QApplication::UnicodeUTF8));
    uiTabVideoIn = new QWidget();
    uiTabVideoIn->setObjectName(QString::fromUtf8("uiTabVideoIn"));
    uiLabelBrightness = new QLabel(uiTabVideoIn);
    uiLabelBrightness->setObjectName(QString::fromUtf8("uiLabelBrightness"));
    uiLabelBrightness->setGeometry(QRect(12, 50, 72, 20));
    uiLabelBrightness->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLabelContrast = new QLabel(uiTabVideoIn);
    uiLabelContrast->setObjectName(QString::fromUtf8("uiLabelContrast"));
    uiLabelContrast->setGeometry(QRect(12, 80, 72, 17));
    uiLabelContrast->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLabelHue = new QLabel(uiTabVideoIn);
    uiLabelHue->setObjectName(QString::fromUtf8("uiLabelHue"));
    uiLabelHue->setGeometry(QRect(12, 20, 72, 17));
    uiLabelHue->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiHSliderBrightness = new QSlider(uiTabVideoIn);
    uiHSliderBrightness->setObjectName(QString::fromUtf8("uiHSliderBrightness"));
    uiHSliderBrightness->setEnabled(true);
    uiHSliderBrightness->setGeometry(QRect(126, 50, 260, 21));
    uiHSliderBrightness->setMaximum(255);
    uiHSliderBrightness->setOrientation(Qt::Horizontal);
    uiHSliderContrast = new QSlider(uiTabVideoIn);
    uiHSliderContrast->setObjectName(QString::fromUtf8("uiHSliderContrast"));
    uiHSliderContrast->setEnabled(true);
    uiHSliderContrast->setGeometry(QRect(126, 80, 260, 21));
    uiHSliderContrast->setMaximum(255);
    uiHSliderContrast->setOrientation(Qt::Horizontal);
    uiLabelHueValue = new QLabel(uiTabVideoIn);
    uiLabelHueValue->setObjectName(QString::fromUtf8("uiLabelHueValue"));
    uiLabelHueValue->setEnabled(true);
    uiLabelHueValue->setGeometry(QRect(96, 20, 20, 17));
    uiLabelBrightnessValue = new QLabel(uiTabVideoIn);
    uiLabelBrightnessValue->setObjectName(QString::fromUtf8("uiLabelBrightnessValue"));
    uiLabelBrightnessValue->setEnabled(true);
    uiLabelBrightnessValue->setGeometry(QRect(96, 50, 20, 17));
    uiLabelContrastValue = new QLabel(uiTabVideoIn);
    uiLabelContrastValue->setObjectName(QString::fromUtf8("uiLabelContrastValue"));
    uiLabelContrastValue->setEnabled(true);
    uiLabelContrastValue->setGeometry(QRect(96, 80, 20, 17));
    uiLabelSaturation = new QLabel(uiTabVideoIn);
    uiLabelSaturation->setObjectName(QString::fromUtf8("uiLabelSaturation"));
    uiLabelSaturation->setGeometry(QRect(12, 110, 72, 20));
    uiLabelSaturation->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiLabelSaturationValue = new QLabel(uiTabVideoIn);
    uiLabelSaturationValue->setObjectName(QString::fromUtf8("uiLabelSaturationValue"));
    uiLabelSaturationValue->setEnabled(true);
    uiLabelSaturationValue->setGeometry(QRect(96, 110, 20, 17));
    uiLabelSharpness = new QLabel(uiTabVideoIn);
    uiLabelSharpness->setObjectName(QString::fromUtf8("uiLabelSharpness"));
    uiLabelSharpness->setGeometry(QRect(12, 140, 72, 20));
    uiLabelSharpness->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiHSliderHue = new QSlider(uiTabVideoIn);
    uiHSliderHue->setObjectName(QString::fromUtf8("uiHSliderHue"));
    uiHSliderHue->setEnabled(true);
    uiHSliderHue->setGeometry(QRect(126, 20, 260, 21));
    uiHSliderHue->setMaximum(255);
    uiHSliderHue->setOrientation(Qt::Horizontal);
    uiChkBoxLiveUpdate = new QCheckBox(uiTabVideoIn);
    uiChkBoxLiveUpdate->setObjectName(QString::fromUtf8("uiChkBoxLiveUpdate"));
    uiChkBoxLiveUpdate->setGeometry(QRect(23, 264, 401, 21));
    uiBtnResetAll = new QPushButton(uiTabVideoIn);
    uiBtnResetAll->setObjectName(QString::fromUtf8("uiBtnResetAll"));
    uiBtnResetAll->setGeometry(QRect(180, 230, 75, 25));
    uiLabelSharpnessValue = new QLabel(uiTabVideoIn);
    uiLabelSharpnessValue->setObjectName(QString::fromUtf8("uiLabelSharpnessValue"));
    uiLabelSharpnessValue->setEnabled(true);
    uiLabelSharpnessValue->setGeometry(QRect(96, 140, 21, 17));
    uiHSliderSaturation = new QSlider(uiTabVideoIn);
    uiHSliderSaturation->setObjectName(QString::fromUtf8("uiHSliderSaturation"));
    uiHSliderSaturation->setEnabled(true);
    uiHSliderSaturation->setGeometry(QRect(126, 110, 260, 21));
    uiHSliderSaturation->setMaximum(255);
    uiHSliderSaturation->setOrientation(Qt::Horizontal);
    uiChkBoxDeinterlacing = new QCheckBox(uiTabVideoIn);
    uiChkBoxDeinterlacing->setObjectName(QString::fromUtf8("uiChkBoxDeinterlacing"));
    uiChkBoxDeinterlacing->setGeometry(QRect(20, 170, 101, 21));
    uiLabelGainMode = new QLabel(uiTabVideoIn);
    uiLabelGainMode->setObjectName(QString::fromUtf8("uiLabelGainMode"));
    uiLabelGainMode->setGeometry(QRect(169, 175, 81, 20));
    uiLabelGainMode->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiHSliderSharpness = new QSlider(uiTabVideoIn);
    uiHSliderSharpness->setObjectName(QString::fromUtf8("uiHSliderSharpness"));
    uiHSliderSharpness->setEnabled(true);
    uiHSliderSharpness->setGeometry(QRect(126, 140, 260, 21));
    uiHSliderSharpness->setMinimum(1);
    uiHSliderSharpness->setMaximum(15);
    uiHSliderSharpness->setOrientation(Qt::Horizontal);
    uiLabelGainModeValue = new QLabel(uiTabVideoIn);
    uiLabelGainModeValue->setObjectName(QString::fromUtf8("uiLabelGainModeValue"));
    uiLabelGainModeValue->setGeometry(QRect(253, 175, 31, 20));
    uiChkBoxNoiseReduction = new QCheckBox(uiTabVideoIn);
    uiChkBoxNoiseReduction->setObjectName(QString::fromUtf8("uiChkBoxNoiseReduction"));
    uiChkBoxNoiseReduction->setGeometry(QRect(20, 201, 121, 21));
    uiLabelCamTermination = new QLabel(uiTabVideoIn);
    uiLabelCamTermination->setObjectName(QString::fromUtf8("uiLabelCamTermination"));
    uiLabelCamTermination->setGeometry(QRect(159, 203, 121, 17));
    uiLabelCamTermination->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    uiHSliderGainMode = new QSlider(uiTabVideoIn);
    uiHSliderGainMode->setObjectName(QString::fromUtf8("uiHSliderGainMode"));
    uiHSliderGainMode->setGeometry(QRect(290, 174, 160, 21));
    uiHSliderGainMode->setMaximum(255);
    uiHSliderGainMode->setOrientation(Qt::Horizontal);
    uiComboBoxCamTermination = new QComboBox(uiTabVideoIn);
    uiComboBoxCamTermination->setObjectName(QString::fromUtf8("uiComboBoxCamTermination"));
    uiComboBoxCamTermination->setGeometry(QRect(290, 201, 141, 22));
    uiTabSettings->addTab(uiTabVideoIn, QApplication::translate("CameraDialog", "Video-In Settings", 0, QApplication::UnicodeUTF8));
    uiTabAudioEncoder = new QWidget();
    uiTabAudioEncoder->setObjectName(QString::fromUtf8("uiTabAudioEncoder"));
    uiLabelAudioEncoder = new QLabel(uiTabAudioEncoder);
    uiLabelAudioEncoder->setObjectName(QString::fromUtf8("uiLabelAudioEncoder"));
    uiLabelAudioEncoder->setGeometry(QRect(20, 20, 91, 17));
    uiLabelAudioEncoderValue = new QLabel(uiTabAudioEncoder);
    uiLabelAudioEncoderValue->setObjectName(QString::fromUtf8("uiLabelAudioEncoderValue"));
    uiLabelAudioEncoderValue->setGeometry(QRect(120, 20, 71, 17));
    uiRadioAlaw = new QRadioButton(uiTabAudioEncoder);
    uiRadioAlaw->setObjectName(QString::fromUtf8("uiRadioAlaw"));
    uiRadioAlaw->setEnabled(false);
    uiRadioAlaw->setGeometry(QRect(116, 63, 191, 21));
    uiRadioUlaw = new QRadioButton(uiTabAudioEncoder);
    uiRadioUlaw->setObjectName(QString::fromUtf8("uiRadioUlaw"));
    uiRadioUlaw->setEnabled(false);
    uiRadioUlaw->setGeometry(QRect(116, 40, 231, 21));
    uiRadioUlaw->setChecked(true);
    uiTabSettings->addTab(uiTabAudioEncoder, QApplication::translate("CameraDialog", "Audio Encoder", 0, QApplication::UnicodeUTF8));
    QWidget::setTabOrder(uiTabSettings, uiHSliderHue);
    QWidget::setTabOrder(uiHSliderHue, uiHSliderBrightness);
    QWidget::setTabOrder(uiHSliderBrightness, uiHSliderContrast);
    QWidget::setTabOrder(uiHSliderContrast, uiHSliderSaturation);
    QWidget::setTabOrder(uiHSliderSaturation, uiHSliderSharpness);
    QWidget::setTabOrder(uiHSliderSharpness, uiChkBoxDeinterlacing);
    QWidget::setTabOrder(uiChkBoxDeinterlacing, uiChkBoxNoiseReduction);
    QWidget::setTabOrder(uiChkBoxNoiseReduction, uiComboBoxCamTermination);
    QWidget::setTabOrder(uiComboBoxCamTermination, uiChkBoxLiveUpdate);
    QWidget::setTabOrder(uiChkBoxLiveUpdate, uiBtnResetAll);
    QWidget::setTabOrder(uiBtnResetAll, uiRadioSubEncPrimary);
    QWidget::setTabOrder(uiRadioSubEncPrimary, uiRadioSubEncSecondary);
    QWidget::setTabOrder(uiRadioSubEncSecondary, buttonBox);
    QWidget::setTabOrder(buttonBox, h264QualityEdit);
    QWidget::setTabOrder(h264QualityEdit, motionThresholdEdit);
    QWidget::setTabOrder(motionThresholdEdit, blindThresholdEdit);
    QWidget::setTabOrder(blindThresholdEdit, nightThresholdEdit);
    QWidget::setTabOrder(nightThresholdEdit, onAlarmEncodingCheck);
    QWidget::setTabOrder(onAlarmEncodingCheck, onAlarmFrameRateEdit);
    QWidget::setTabOrder(onAlarmFrameRateEdit, onAlarmMinOnEdit);
    QWidget::setTabOrder(onAlarmMinOnEdit, onAlarmMinOffEdit);
    QWidget::setTabOrder(onAlarmMinOffEdit, uiLEditEncOnAlarmMjpegQuality);
    QWidget::setTabOrder(uiLEditEncOnAlarmMjpegQuality, onAlarmBitRateControlCombo);
    QWidget::setTabOrder(onAlarmBitRateControlCombo, onAlarmAvgBitRateEdit);
    QWidget::setTabOrder(onAlarmAvgBitRateEdit, onAlarmMaxBitRateEdit);
    QWidget::setTabOrder(onAlarmMaxBitRateEdit, onAlarmH264QualityEdit);
    QWidget::setTabOrder(onAlarmH264QualityEdit, onAlarmGOPSizeEdit);
    QWidget::setTabOrder(onAlarmGOPSizeEdit, jpegQualityEdit);
    QWidget::setTabOrder(jpegQualityEdit, uiLEditAvgBitRateMPEG4);
    QWidget::setTabOrder(uiLEditAvgBitRateMPEG4, uiLEditMaxBitRateMPEG4);
    QWidget::setTabOrder(uiLEditMaxBitRateMPEG4, uiLEditQualityMPEG4);
    QWidget::setTabOrder(uiLEditQualityMPEG4, uiLEditEncOnAlarmGOPMPEG4);
    QWidget::setTabOrder(uiLEditEncOnAlarmGOPMPEG4, uiComboEncOnAlarmBitRateControlMPEG4);
    QWidget::setTabOrder(uiComboEncOnAlarmBitRateControlMPEG4, uiLEditEncOnAlarmAvgBitRateMPEG4);
    QWidget::setTabOrder(uiLEditEncOnAlarmAvgBitRateMPEG4, uiLEditEncOnAlarmMaxBitRateMPEG4);
    QWidget::setTabOrder(uiLEditEncOnAlarmMaxBitRateMPEG4, uiLEditEncOnAlarmQualityMPEG4);
    QWidget::setTabOrder(uiLEditEncOnAlarmQualityMPEG4, uiBtnBlindRegions);
    QWidget::setTabOrder(uiBtnBlindRegions, uiBtnMotionRegions);
    QWidget::setTabOrder(uiBtnMotionRegions, uiBtnPrivacyRegions);
    QWidget::setTabOrder(uiBtnPrivacyRegions, uiRadioAlaw);
    QWidget::setTabOrder(uiRadioAlaw, uiRadioUlaw);
    QWidget::setTabOrder(uiRadioUlaw, uiComboBitRateControlMPEG4);
    QWidget::setTabOrder(uiComboBitRateControlMPEG4, avgBitRateEdit);
    QWidget::setTabOrder(avgBitRateEdit, frameRateEdit);
    QWidget::setTabOrder(frameRateEdit, uiLEditEncGOPMPEG4);
    QWidget::setTabOrder(uiLEditEncGOPMPEG4, GOPSizeEdit);
    QWidget::setTabOrder(GOPSizeEdit, decimationCombo);
    QWidget::setTabOrder(decimationCombo, bitRateControlCombo);
    QWidget::setTabOrder(bitRateControlCombo, cameraNameEdit);
    QWidget::setTabOrder(cameraNameEdit, uiSpinBoxOSDNum);
    QWidget::setTabOrder(uiSpinBoxOSDNum, osdTextEdit);
    QWidget::setTabOrder(osdTextEdit, osdLocationCombo);
    QWidget::setTabOrder(osdLocationCombo, uiLEditTLy);
    QWidget::setTabOrder(uiLEditTLy, uiLEditTLx);
    QWidget::setTabOrder(uiLEditTLx, uiComboMDThresholds);
    QWidget::setTabOrder(uiComboMDThresholds, uiLEditMotionValueFreq);
    QWidget::setTabOrder(uiLEditMotionValueFreq, maxBitRateEdit);
    QWidget::setTabOrder(maxBitRateEdit, uiSpinBoxRawVideoFrameRate);
    QWidget::setTabOrder(uiSpinBoxRawVideoFrameRate, uiHSliderTranslucent);
    QWidget::setTabOrder(uiHSliderTranslucent, osdDtsFormatCombo);
    QWidget::setTabOrder(osdDtsFormatCombo, uiChkBoxOSDShow);

    retranslateUi(CameraDialog);

    QSize size(492, 392);
    size = size.expandedTo(CameraDialog->minimumSizeHint());
    CameraDialog->resize(size);

    QObject::connect(buttonBox, SIGNAL(accepted()), CameraDialog, SLOT(accept()));
    QObject::connect(buttonBox, SIGNAL(rejected()), CameraDialog, SLOT(reject()));

    uiTabSettings->setCurrentIndex(0);


    QMetaObject::connectSlotsByName(CameraDialog);
    } // setupUi

    void retranslateUi(QDialog *CameraDialog)
    {
    CameraDialog->setWindowTitle(QApplication::translate("CameraDialog", "Camera Settings", 0, QApplication::UnicodeUTF8));
    uiGrpSubEncoder->setTitle(QApplication::translate("CameraDialog", "Sub-Encoder", 0, QApplication::UnicodeUTF8));
    uiRadioSubEncSecondary->setText(QApplication::translate("CameraDialog", "Secondary", 0, QApplication::UnicodeUTF8));
    uiRadioSubEncPrimary->setText(QApplication::translate("CameraDialog", "Primary", 0, QApplication::UnicodeUTF8));
    uiTabSettings->setToolTip(QString());
    uiTabSettings->setWhatsThis(QString());
    label_1->setText(QApplication::translate("CameraDialog", "Camera Name:", 0, QApplication::UnicodeUTF8));
    label_23->setText(QApplication::translate("CameraDialog", "Raw Video Frame Rate:", 0, QApplication::UnicodeUTF8));
    uiSpinBoxRawVideoFrameRate->setToolTip(QString());
    uiSpinBoxRawVideoFrameRate->setWhatsThis(QApplication::translate("CameraDialog", "Enter the rate at which each raw video frame is received from the DVR Board.", 0, QApplication::UnicodeUTF8));
    osdGroup->setTitle(QApplication::translate("CameraDialog", "OSD", 0, QApplication::UnicodeUTF8));
    label_14->setText(QApplication::translate("CameraDialog", "Text:", 0, QApplication::UnicodeUTF8));
    uiLableOSDTextNum->setText(QApplication::translate("CameraDialog", "OSD #:", 0, QApplication::UnicodeUTF8));
    label_16->setText(QApplication::translate("CameraDialog", "Location:", 0, QApplication::UnicodeUTF8));
    osdTextEdit->setText(QString());
    osdDtsGroup->setTitle(QApplication::translate("CameraDialog", "Time Stamp", 0, QApplication::UnicodeUTF8));
    label_15->setText(QApplication::translate("CameraDialog", "Format:", 0, QApplication::UnicodeUTF8));
    uiChkBoxOSDShow->setText(QApplication::translate("CameraDialog", "Show", 0, QApplication::UnicodeUTF8));
    uiLableTLy->setText(QApplication::translate("CameraDialog", "Top Left y:", 0, QApplication::UnicodeUTF8));
    uiLableTLx->setText(QApplication::translate("CameraDialog", "Top Left x:", 0, QApplication::UnicodeUTF8));
    uiLabelTranslucent->setText(QApplication::translate("CameraDialog", "Text Translucent:", 0, QApplication::UnicodeUTF8));
    uiLabelTranslucentValue->setText(QApplication::translate("CameraDialog", "0", 0, QApplication::UnicodeUTF8));
    uiTabSettings->setTabText(uiTabSettings->indexOf(generalTab), QApplication::translate("CameraDialog", "General", 0, QApplication::UnicodeUTF8));
    JPEGGroup->setTitle(QApplication::translate("CameraDialog", "MJPEG", 0, QApplication::UnicodeUTF8));
    label_8->setText(QApplication::translate("CameraDialog", "Quality:", 0, QApplication::UnicodeUTF8));
    uiGrpEncMPEG4->setTitle(QApplication::translate("CameraDialog", "MPEG4", 0, QApplication::UnicodeUTF8));
    label_25->setText(QApplication::translate("CameraDialog", "Bit Rate Control:", 0, QApplication::UnicodeUTF8));
    label_26->setText(QApplication::translate("CameraDialog", "Average Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_27->setText(QApplication::translate("CameraDialog", "Maximum Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_24->setText(QApplication::translate("CameraDialog", "GOP size:", 0, QApplication::UnicodeUTF8));
    uiLEditAvgBitRateMPEG4->setToolTip(QApplication::translate("CameraDialog", "from 1 - 10", 0, QApplication::UnicodeUTF8));
    uiLEditAvgBitRateMPEG4->setWhatsThis(QApplication::translate("CameraDialog", "what is it?", 0, QApplication::UnicodeUTF8));
    uiLabelQualityMPEG4->setText(QApplication::translate("CameraDialog", "Quality:", 0, QApplication::UnicodeUTF8));
    label_2->setText(QApplication::translate("CameraDialog", "Decimation:", 0, QApplication::UnicodeUTF8));
    label_3->setText(QApplication::translate("CameraDialog", "Frame Rate:", 0, QApplication::UnicodeUTF8));
    H264Group->setTitle(QApplication::translate("CameraDialog", "H.264", 0, QApplication::UnicodeUTF8));
    label_6->setText(QApplication::translate("CameraDialog", "Average Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_17->setText(QApplication::translate("CameraDialog", "Maximum Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_7->setText(QApplication::translate("CameraDialog", "Quality:", 0, QApplication::UnicodeUTF8));
    label_5->setText(QApplication::translate("CameraDialog", "Bit Rate Control:", 0, QApplication::UnicodeUTF8));
    label_4->setText(QApplication::translate("CameraDialog", "GOP size:", 0, QApplication::UnicodeUTF8));
    avgBitRateEdit->setToolTip(QString());
    avgBitRateEdit->setWhatsThis(QString());
    uiTabSettings->setTabText(uiTabSettings->indexOf(encodingTab), QApplication::translate("CameraDialog", "Video Encoder", 0, QApplication::UnicodeUTF8));
    blindDetectionGroup->setTitle(QApplication::translate("CameraDialog", "Blind Detection", 0, QApplication::UnicodeUTF8));
    label_10->setText(QApplication::translate("CameraDialog", "Threshold:", 0, QApplication::UnicodeUTF8));
    uiBtnBlindRegions->setText(QApplication::translate("CameraDialog", "Regions...", 0, QApplication::UnicodeUTF8));
    nightDetectionGroup->setTitle(QApplication::translate("CameraDialog", "Night Detection", 0, QApplication::UnicodeUTF8));
    label_9->setText(QApplication::translate("CameraDialog", "Threshold:", 0, QApplication::UnicodeUTF8));
    motionDetectionGroup->setTitle(QApplication::translate("CameraDialog", "Motion Detection", 0, QApplication::UnicodeUTF8));
    uiBtnMotionRegions->setText(QApplication::translate("CameraDialog", "Regions...", 0, QApplication::UnicodeUTF8));
    privacyProtectionGroup->setTitle(QApplication::translate("CameraDialog", "Privacy Protection", 0, QApplication::UnicodeUTF8));
    uiBtnPrivacyRegions->setText(QApplication::translate("CameraDialog", "Regions...", 0, QApplication::UnicodeUTF8));
    uiLabelMotionValueFreq->setText(QApplication::translate("CameraDialog", "Motion Value Frame Frequency:", 0, QApplication::UnicodeUTF8));
    uiTabSettings->setTabText(uiTabSettings->indexOf(alarmsTab), QApplication::translate("CameraDialog", "Alarms", 0, QApplication::UnicodeUTF8));
    uiGrpEncOnAlarmMPEG4->setTitle(QApplication::translate("CameraDialog", "MPEG4", 0, QApplication::UnicodeUTF8));
    label_33->setText(QApplication::translate("CameraDialog", "Maximum Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_34->setText(QApplication::translate("CameraDialog", "Bit Rate Control:", 0, QApplication::UnicodeUTF8));
    label_35->setText(QApplication::translate("CameraDialog", "Average Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_37->setText(QApplication::translate("CameraDialog", "GOP Size:", 0, QApplication::UnicodeUTF8));
    uiLabelEncOnAlarmQualityMPEG4->setText(QApplication::translate("CameraDialog", "Quality:", 0, QApplication::UnicodeUTF8));
    uiGrpEncOnAlarmMjpeg->setTitle(QApplication::translate("CameraDialog", "MJPEG", 0, QApplication::UnicodeUTF8));
    uiLabelEncOnAlarmMjpegQuality->setText(QApplication::translate("CameraDialog", "Quality:", 0, QApplication::UnicodeUTF8));
    label_20->setText(QApplication::translate("CameraDialog", "Minimum Off Time:", 0, QApplication::UnicodeUTF8));
    label->setText(QApplication::translate("CameraDialog", "Minimum On Time:", 0, QApplication::UnicodeUTF8));
    label_21->setText(QApplication::translate("CameraDialog", "Frame Rate:", 0, QApplication::UnicodeUTF8));
    uiGrpEncOnAlarmH264->setTitle(QApplication::translate("CameraDialog", "H.264", 0, QApplication::UnicodeUTF8));
    label_18->setText(QApplication::translate("CameraDialog", "Maximum Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_13->setText(QApplication::translate("CameraDialog", "Bit Rate Control:", 0, QApplication::UnicodeUTF8));
    label_12->setText(QApplication::translate("CameraDialog", "Average Bit Rate:", 0, QApplication::UnicodeUTF8));
    label_22->setText(QApplication::translate("CameraDialog", "Quality:", 0, QApplication::UnicodeUTF8));
    label_19->setText(QApplication::translate("CameraDialog", "GOP Size:", 0, QApplication::UnicodeUTF8));
    onAlarmEncodingCheck->setText(QApplication::translate("CameraDialog", "Adjust Encoding on Alarm", 0, QApplication::UnicodeUTF8));
    uiTabSettings->setTabText(uiTabSettings->indexOf(uiTabEncOnAlarm), QApplication::translate("CameraDialog", "Video Encoder on Alarm", 0, QApplication::UnicodeUTF8));
    uiLabelBrightness->setText(QApplication::translate("CameraDialog", "Brightness:", 0, QApplication::UnicodeUTF8));
    uiLabelContrast->setText(QApplication::translate("CameraDialog", "Contrast:", 0, QApplication::UnicodeUTF8));
    uiLabelHue->setText(QApplication::translate("CameraDialog", "Hue:", 0, QApplication::UnicodeUTF8));
    uiLabelHueValue->setText(QApplication::translate("CameraDialog", "0", 0, QApplication::UnicodeUTF8));
    uiLabelBrightnessValue->setText(QApplication::translate("CameraDialog", "0", 0, QApplication::UnicodeUTF8));
    uiLabelContrastValue->setText(QApplication::translate("CameraDialog", "0", 0, QApplication::UnicodeUTF8));
    uiLabelSaturation->setText(QApplication::translate("CameraDialog", "Saturation:", 0, QApplication::UnicodeUTF8));
    uiLabelSaturationValue->setText(QApplication::translate("CameraDialog", "0", 0, QApplication::UnicodeUTF8));
    uiLabelSharpness->setText(QApplication::translate("CameraDialog", "Sharpness:", 0, QApplication::UnicodeUTF8));
    uiChkBoxLiveUpdate->setText(QApplication::translate("CameraDialog", "Live Update the Video-in Frames as Settings are Being Changed", 0, QApplication::UnicodeUTF8));
    uiBtnResetAll->setText(QApplication::translate("CameraDialog", "Reset All", 0, QApplication::UnicodeUTF8));
    uiLabelSharpnessValue->setText(QApplication::translate("CameraDialog", "0", 0, QApplication::UnicodeUTF8));
    uiChkBoxDeinterlacing->setText(QApplication::translate("CameraDialog", "Deinterlacing", 0, QApplication::UnicodeUTF8));
    uiLabelGainMode->setText(QApplication::translate("CameraDialog", "Gain Mode:", 0, QApplication::UnicodeUTF8));
    uiLabelGainModeValue->setText(QApplication::translate("CameraDialog", "0", 0, QApplication::UnicodeUTF8));
    uiChkBoxNoiseReduction->setText(QApplication::translate("CameraDialog", "Noise Reduction", 0, QApplication::UnicodeUTF8));
    uiLabelCamTermination->setText(QApplication::translate("CameraDialog", "Camera Termination:", 0, QApplication::UnicodeUTF8));
    uiTabSettings->setTabText(uiTabSettings->indexOf(uiTabVideoIn), QApplication::translate("CameraDialog", "Video-In Settings", 0, QApplication::UnicodeUTF8));
    uiLabelAudioEncoder->setText(QApplication::translate("CameraDialog", "Audio Encoder:", 0, QApplication::UnicodeUTF8));
    uiLabelAudioEncoderValue->setText(QApplication::translate("CameraDialog", "G711", 0, QApplication::UnicodeUTF8));
    uiRadioAlaw->setText(QApplication::translate("CameraDialog", "Asia and Europe (ALAW)", 0, QApplication::UnicodeUTF8));
    uiRadioUlaw->setText(QApplication::translate("CameraDialog", "North America and Japan (ULAW)", 0, QApplication::UnicodeUTF8));
    uiTabSettings->setTabText(uiTabSettings->indexOf(uiTabAudioEncoder), QApplication::translate("CameraDialog", "Audio Encoder", 0, QApplication::UnicodeUTF8));
    Q_UNUSED(CameraDialog);
    } // retranslateUi

};

namespace Ui {
    class CameraDialog: public Ui_CameraDialog {};
} // namespace Ui

#endif // UI_CAMERADIALOG_H
