# Makefile - NonBlockingPTZWithSendPTZCommand

.PHONY: all
all: \
 	NonBlockingPTZWithSendPTZCommand


.PHONY: NonBlockingPTZWithSendPTZCommand
NonBlockingPTZWithSendPTZCommand:
	cd ../vcproj/ && $(MAKE) -f NonBlockingPTZWithSendPTZCommand.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f NonBlockingPTZWithSendPTZCommand.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f NonBlockingPTZWithSendPTZCommand.mak depends

