# Makefile - NonBlockingPTZWithMoveCamera

.PHONY: all
all: \
 	NonBlockingPTZWithMoveCamera


.PHONY: NonBlockingPTZWithMoveCamera
NonBlockingPTZWithMoveCamera:
	cd ../vcproj/ && $(MAKE) -f NonBlockingPTZWithMoveCamera.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f NonBlockingPTZWithMoveCamera.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f NonBlockingPTZWithMoveCamera.mak depends

