# Makefile - ePTZ

.PHONY: all
all: \
 	ePTZ


.PHONY: ePTZ
ePTZ:
	cd ../vcproj/ && $(MAKE) -f ePTZ.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f ePTZ.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f ePTZ.mak depends

