# Makefile - PresentLocation

.PHONY: all
all: \
 	PresentLocation


.PHONY: PresentLocation
PresentLocation:
	cd ../vcproj/ && $(MAKE) -f PresentLocation.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f PresentLocation.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f PresentLocation.mak depends

