# Makefile - ConnectMultipleStreamDevice

.PHONY: all
all: \
 	ConnectMultipleStreamDevice


.PHONY: ConnectMultipleStreamDevice
ConnectMultipleStreamDevice:
	cd ../vcproj/ && $(MAKE) -f ConnectMultipleStreamDevice.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f ConnectMultipleStreamDevice.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f ConnectMultipleStreamDevice.mak depends

