# Makefile - SendHTTPCommandBlock

.PHONY: all
all: \
 	SendHTTPCommandBlock


.PHONY: SendHTTPCommandBlock
SendHTTPCommandBlock:
	cd ../vcproj/ && $(MAKE) -f SendHTTPCommandBlock.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f SendHTTPCommandBlock.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f SendHTTPCommandBlock.mak depends

