# Makefile - SSLSupport

.PHONY: all
all: \
 	SSLSupport


.PHONY: SSLSupport
SSLSupport:
	cd ../vcproj/ && $(MAKE) -f SSLSupport.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f SSLSupport.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f SSLSupport.mak depends

