# Makefile - ConnectToDevice

.PHONY: all
all: \
 	ConnectToDevice


.PHONY: ConnectToDevice
ConnectToDevice:
	cd ../vcproj/ && $(MAKE) -f ConnectToDevice.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f ConnectToDevice.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f ConnectToDevice.mak depends

