# Makefile - PTZWithSendPTZCommand

.PHONY: all
all: \
 	PTZWithSendPTZCommand


.PHONY: PTZWithSendPTZCommand
PTZWithSendPTZCommand:
	cd ../vcproj/ && $(MAKE) -f PTZWithSendPTZCommand.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f PTZWithSendPTZCommand.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f PTZWithSendPTZCommand.mak depends

