# Makefile - Reconnect

.PHONY: all
all: \
 	Reconnect


.PHONY: Reconnect
Reconnect:
	cd  ../vcproj/ && $(MAKE) -f Reconnect.mak

.PHONY: clean
clean:
	cd  ../vcproj/ && $(MAKE) -f Reconnect.mak clean

.PHONY: depends
depends:
	cd  ../vcproj/ && $(MAKE) -f Reconnect.mak depends

