# Makefile - DecoderChannel

.PHONY: all
all: \
 	DecoderChannel


.PHONY: DecoderChannel
DecoderChannel:
	$(MAKE) -f DecoderChannel.mak

.PHONY: clean
clean:
	$(MAKE) -f DecoderChannel.mak clean

.PHONY: depends
depends:
	$(MAKE) -f DecoderChannel.mak depends

