# Makefile - PTZWithMoveCamera

.PHONY: all
all: \
 	PTZWithMoveCamera


.PHONY: PTZWithMoveCamera
PTZWithMoveCamera:
	cd ../vcproj/ && $(MAKE) -f PTZWithMoveCamera.mak

.PHONY: clean
clean:
	cd ../vcproj/ && $(MAKE) -f PTZWithMoveCamera.mak clean

.PHONY: depends
depends:
	cd ../vcproj/ && $(MAKE) -f PTZWithMoveCamera.mak depends

